//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTLogApp
    {
        public long IdLogApp { get; set; }
        public string Type { get; set; }
        public string GUID { get; set; }
        public string AppName { get; set; }
        public string WebServiceName { get; set; }
        public string MethodName { get; set; }
        public string MethodNameUI { get; set; }
        public string UserName { get; set; }
        public string UserMachineInfo { get; set; }
        public string ServerIP { get; set; }
        public string Data { get; set; }
        public string ErrorMessage { get; set; }
        public string Source { get; set; }
        public string Method { get; set; }
        public string ErrorType { get; set; }
        public string Trace { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
