//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTLogConsultasAni : EntityBase
    {
        public long IdConsulta { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string Nuip { get; set; }
        public string Origen { get; set; }
        public System.DateTime FechaInicia { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int Duracion { get; set; }
        public Nullable<int> IdCcf { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string IdRptaRnec { get; set; }
        public string IdRptaAsocajas { get; set; }
    
        public virtual RCCF RCCF { get; set; }
        public virtual RRptaAsocajas RRptaAsocajas { get; set; }
        public virtual RRptaRnec RRptaRnec { get; set; }
        public virtual RUsuario RUsuario { get; set; }
    }
}
