//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas
{
    using System;
    using System.Collections.Generic;
    using Asocajas.Common.Supertype;
    public partial class RDatoBasico : EntityBase
    {
        public long IdDatoBasico { get; set; }
        public Nullable<long> IdDatoBasicoPadre { get; set; }
        public int IdTipoDatoBasico { get; set; }
        public string Descripcion { get; set; }
        public string Code { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string MaquinaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public string MaquinaActualizacion { get; set; }
        public bool Activo { get; set; }
    }
}
