//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas
{
    using System;
    using System.Collections.Generic;
    using Asocajas.Common.Supertype;
    public partial class RMenu : EntityBase
    {
        public int IdMenu { get; set; }
        public Nullable<int> IdMenuHijo { get; set; }
        public int IdRole { get; set; }
        public string Descripcion { get; set; }
        public int Orden { get; set; }
        public string url { get; set; }
    }
}
