//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas
{
    using System;
    using System.Collections.Generic;
    using Asocajas.Common.Supertype;
    public partial class ROrigen : EntityBase
    {
        public ROrigen()
        {
            this.LTLogConsultasAni = new HashSet<LTLogConsultasAni>();
        }
    
        public string IdOrigen { get; set; }
        public string OrigenConsulta { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<LTLogConsultasAni> LTLogConsultasAni { get; set; }
    }
}
