//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas
{
    using System;
    using System.Collections.Generic;
    using Asocajas.Common.Supertype;
    public partial class RRole : EntityBase
    {
        public RRole()
        {
            this.RUsuario = new HashSet<RUsuario>();
        }
    
        public int IdRole { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string MaquinaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public string MaquinaActualizacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<RUsuario> RUsuario { get; set; }
    }
}
