//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas
{
    using System;
    using System.Collections.Generic;
    using Asocajas.Common.Supertype;
    public partial class RRptaAsocajas : EntityBase
    {
        public string IdRptaAsocajas { get; set; }
        public string RptaAsocajas { get; set; }
        public bool Activo { get; set; }
    }
}
