//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asocajas.ConsultaListaCedulas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultaListaCedulas.ValidateInfoServiceSoap")]
    public interface ValidateInfoServiceSoap {
        
        // CODEGEN: Generating message contract since message ListaDataCedulasRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDataCedulas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Asocajas.ConsultaListaCedulas.ListaDataCedulasResponse ListaDataCedulas(Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDataCedulas", ReplyAction="*")]
        System.Threading.Tasks.Task<Asocajas.ConsultaListaCedulas.ListaDataCedulasResponse> ListaDataCedulasAsync(Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConectUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private string ipField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("ip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class datosCedulas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string anoResolucionField;
        
        private string codErrorField;
        
        private string departamentoExpedicionField;
        
        private string estadoCedulaField;
        
        private string fechaDefuncionField;
        
        private string fechaExpedicionField;
        
        private string fechaNacimientoField;
        
        private string generoField;
        
        private string informanteField;
        
        private string lugarNacimientoField;
        
        private string lugarNovedadField;
        
        private string lugarPreparacionField;
        
        private string municipioExpedicionField;
        
        private string nuipField;
        
        private string numResolucionField;
        
        private string particulaField;
        
        private string primerApellidoField;
        
        private string primerNombreField;
        
        private string segundoApellidoField;
        
        private string segundoNombreField;
        
        private string serialField;
        
        private string descripcionErrorField;
        
        private string fechaHoraConsultaField;
        
        private string numeroControlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string anoResolucion {
            get {
                return this.anoResolucionField;
            }
            set {
                this.anoResolucionField = value;
                this.RaisePropertyChanged("anoResolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codError {
            get {
                return this.codErrorField;
            }
            set {
                this.codErrorField = value;
                this.RaisePropertyChanged("codError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string departamentoExpedicion {
            get {
                return this.departamentoExpedicionField;
            }
            set {
                this.departamentoExpedicionField = value;
                this.RaisePropertyChanged("departamentoExpedicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string estadoCedula {
            get {
                return this.estadoCedulaField;
            }
            set {
                this.estadoCedulaField = value;
                this.RaisePropertyChanged("estadoCedula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string fechaDefuncion {
            get {
                return this.fechaDefuncionField;
            }
            set {
                this.fechaDefuncionField = value;
                this.RaisePropertyChanged("fechaDefuncion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fechaExpedicion {
            get {
                return this.fechaExpedicionField;
            }
            set {
                this.fechaExpedicionField = value;
                this.RaisePropertyChanged("fechaExpedicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string informante {
            get {
                return this.informanteField;
            }
            set {
                this.informanteField = value;
                this.RaisePropertyChanged("informante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string lugarNacimiento {
            get {
                return this.lugarNacimientoField;
            }
            set {
                this.lugarNacimientoField = value;
                this.RaisePropertyChanged("lugarNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string lugarNovedad {
            get {
                return this.lugarNovedadField;
            }
            set {
                this.lugarNovedadField = value;
                this.RaisePropertyChanged("lugarNovedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string lugarPreparacion {
            get {
                return this.lugarPreparacionField;
            }
            set {
                this.lugarPreparacionField = value;
                this.RaisePropertyChanged("lugarPreparacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string municipioExpedicion {
            get {
                return this.municipioExpedicionField;
            }
            set {
                this.municipioExpedicionField = value;
                this.RaisePropertyChanged("municipioExpedicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string nuip {
            get {
                return this.nuipField;
            }
            set {
                this.nuipField = value;
                this.RaisePropertyChanged("nuip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string numResolucion {
            get {
                return this.numResolucionField;
            }
            set {
                this.numResolucionField = value;
                this.RaisePropertyChanged("numResolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string particula {
            get {
                return this.particulaField;
            }
            set {
                this.particulaField = value;
                this.RaisePropertyChanged("particula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string primerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
                this.RaisePropertyChanged("primerNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
                this.RaisePropertyChanged("segundoNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string fechaHoraConsulta {
            get {
                return this.fechaHoraConsultaField;
            }
            set {
                this.fechaHoraConsultaField = value;
                this.RaisePropertyChanged("fechaHoraConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string numeroControl {
            get {
                return this.numeroControlField;
            }
            set {
                this.numeroControlField = value;
                this.RaisePropertyChanged("numeroControl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class estadoConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroControlField;
        
        private string codErrorField;
        
        private string descripcionErrorField;
        
        private System.DateTime fechaHoraConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroControl {
            get {
                return this.numeroControlField;
            }
            set {
                this.numeroControlField = value;
                this.RaisePropertyChanged("numeroControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codError {
            get {
                return this.codErrorField;
            }
            set {
                this.codErrorField = value;
                this.RaisePropertyChanged("codError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime fechaHoraConsulta {
            get {
                return this.fechaHoraConsultaField;
            }
            set {
                this.fechaHoraConsultaField = value;
                this.RaisePropertyChanged("fechaHoraConsulta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoConsulta estadoConsultaField;
        
        private datosCedulas datosCedulasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public estadoConsulta estadoConsulta {
            get {
                return this.estadoConsultaField;
            }
            set {
                this.estadoConsultaField = value;
                this.RaisePropertyChanged("estadoConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public datosCedulas datosCedulas {
            get {
                return this.datosCedulasField;
            }
            set {
                this.datosCedulasField = value;
                this.RaisePropertyChanged("datosCedulas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaDataCedulas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListaDataCedulasRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Asocajas.ConsultaListaCedulas.ConectUser ConectUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] cedulas;
        
        public ListaDataCedulasRequest() {
        }
        
        public ListaDataCedulasRequest(Asocajas.ConsultaListaCedulas.ConectUser ConectUser, string[] cedulas) {
            this.ConectUser = ConectUser;
            this.cedulas = cedulas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaDataCedulasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListaDataCedulasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Asocajas.ConsultaListaCedulas.Usuario[] ListaDataCedulasResult;
        
        public ListaDataCedulasResponse() {
        }
        
        public ListaDataCedulasResponse(Asocajas.ConsultaListaCedulas.Usuario[] ListaDataCedulasResult) {
            this.ListaDataCedulasResult = ListaDataCedulasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidateInfoServiceSoapChannel : Asocajas.ConsultaListaCedulas.ValidateInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateInfoServiceSoapClient : System.ServiceModel.ClientBase<Asocajas.ConsultaListaCedulas.ValidateInfoServiceSoap>, Asocajas.ConsultaListaCedulas.ValidateInfoServiceSoap {
        
        public ValidateInfoServiceSoapClient() {
        }
        
        public ValidateInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Asocajas.ConsultaListaCedulas.ListaDataCedulasResponse Asocajas.ConsultaListaCedulas.ValidateInfoServiceSoap.ListaDataCedulas(Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest request) {
            return base.Channel.ListaDataCedulas(request);
        }
        
        public Asocajas.ConsultaListaCedulas.Usuario[] ListaDataCedulas(Asocajas.ConsultaListaCedulas.ConectUser ConectUser, string[] cedulas) {
            Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest inValue = new Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest();
            inValue.ConectUser = ConectUser;
            inValue.cedulas = cedulas;
            Asocajas.ConsultaListaCedulas.ListaDataCedulasResponse retVal = ((Asocajas.ConsultaListaCedulas.ValidateInfoServiceSoap)(this)).ListaDataCedulas(inValue);
            return retVal.ListaDataCedulasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Asocajas.ConsultaListaCedulas.ListaDataCedulasResponse> Asocajas.ConsultaListaCedulas.ValidateInfoServiceSoap.ListaDataCedulasAsync(Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest request) {
            return base.Channel.ListaDataCedulasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Asocajas.ConsultaListaCedulas.ListaDataCedulasResponse> ListaDataCedulasAsync(Asocajas.ConsultaListaCedulas.ConectUser ConectUser, string[] cedulas) {
            Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest inValue = new Asocajas.ConsultaListaCedulas.ListaDataCedulasRequest();
            inValue.ConectUser = ConectUser;
            inValue.cedulas = cedulas;
            return ((Asocajas.ConsultaListaCedulas.ValidateInfoServiceSoap)(this)).ListaDataCedulasAsync(inValue);
        }
    }
}
